"new:\n"
"ldw $ar, ($lb) -4\n"
"push $ar\n"
"insc AllocMem\n"
"mov $r1, 1\n"
"stw $r1, ($ar) 0\n"
"ldw $r1, ($lb) -8\n"
"stw $r1, ($ar) 4\n"
"ldw $r1, ($lb) -12\n"
"stw $r1, ($ar) 8\n"
"ret 3\n"
"inc_ref:\n"
"mov $cf, $xr\n"
"je .end\n"
"ldw $r0, ($xr) 0\n"
"inc $r0\n"
"stw $r0, ($xr) 0\n"
".end:\n"
"ret\n"
"dec_ref:\n"
"mov $cf, $xr\n"
"je .end\n"
"ldw $r0, ($xr) 0\n"
"sub $cf, $r0, 1\n"
"je .rel\n"
"dec $r0\n"
"stw $r0, ($xr) 0\n"
"ret\n"
".rel:\n"
"ldw $r0, ($xr) 8\n"
"ldw $r0, ($r0) 0\n"
"push $xr\n"
"call $r0\n"
"insc FreeMem\n"
".end:\n"
"ret\n"
"dynamic_cast:\n"
"ldw $cf, ($lb) -4\n"
"je .end\n"
"mov $ar, $cf\n"
"ldw $r1, ($ar) 4\n"
"ldw $r2, ($lb) -8\n"
"ldw $r3, ($lb) -12\n"
"add $r3, $r3, $r2\n"
"cmp $r2, $r1\n"
"jg .end\n"
"cmp $r1, $r3\n"
"jg .end\n"
"ret 3\n"
".end:\n"
"mov $ar, 0\n"
"ret 3\n"
"resize_buffer:\n"
"ldw $r0, ($lb) -4\n"
"ldw $r1, ($xr) 16\n"
"cmp $r0, $r1\n"
"jle .else\n"
"ldw $r2, ($xr) 12\n"
"ldw $r3, ($xr) 20\n"
"sll $r4, $r0, 1\n"
"push $r4\n"
"insc AllocMem\n"
"stw $ar, ($xr) 20\n"
"stw $r4, ($xr) 16\n"
"push $r2\n"
"push $r3\n"
"push $ar\n"
"insc CopyMem\n"
"push $r3\n"
"insc FreeMem\n"
"push 0\n"
"sub $r3, $r0, $r2\n"
"push $r3\n"
"add $r3, $r4, $r2\n"
"push $r3\n"
"insc FillMem\n"
"jmp .end\n"
".else:\n"
"sub $cf, $r0, $r1\n"
"sub $cf, $cf, $r1\n"
"jge .end\n"
"ldw $r2, ($xr) 12\n"
"ldw $r3, ($xr) 20\n"
"push $r0\n"
"insc AllocMem\n"
"stw $ar, ($xr) 20\n"
"stw $r4, ($xr) 16\n"
"push $r0\n"
"push $r3\n"
"push $ar\n"
"insc CopyMem\n"
"push $r3\n"
"insc FreeMem\n"
".end:\n"
"stw $r0, ($xr) 12\n"
"ret 1\n"
"String.copy_literal:\n"
"ldw $r0, ($lb) -4\n"
"push 24\n"
"insc AllocMem\n"
"mov $xr, $ar\n"
"push $r0\n"
"call CString.Pinit,R@String?source\n"
"mov $ar, $xr\n"
"ret 1\n"
"CObject.Prelease:\n"
"CObject.Pinit:\n"
"ret\n"
"CObject.PrefCount:\n"
"ldw $ar, ($xr) 0\n"
"ret\n"
"CObject.PtypeID:\n"
"ldw $ar, ($xr) 4\n"
"ret\n"
"CObject.Pequals,R@Object?rhs:\n"
"ldw $cf, ($lb) -4\n"
"je .false\n"
"ldw $r0, ($xr) 4\n"
"ldw $r1, ($cf) 4\n"
"cmp $r0, $r1\n"
"jne .false\n"
"mov $ar, 1\n"
"ret 1\n"
".false:\n"
"mov $ar, 0\n"
"ret 1\n"
"CObject.PtoString:\n"
"mov $ar, 0\n"
"ret\n"
"CObject.Ppointer:\n"
"add $ar, $xr, 12\n"
"ret\n"
"Object.vtable:\n"
".word @CObject.Prelease\n"
".word @CObject.Pinit\n"
".word @CObject.PtypeID\n"
".word @CObject.PrefCount\n"
".word @CObject.Pequals,R@Object?rhs\n"
".word @CObject.PtoString\n"
".word @CObject.Ppointer\n"
"CString.Prelease:\n"
"ldw $r0, ($xr) 20\n"
"push $r0\n"
"insc FreeMem\n"
"ret\n"
"CString.Pinit:\n"
"mov $r0, 1\n"
"stw $r0, ($xr) 12\n"
"mov $r1, 16\n"
"stw $r1, ($xr) 16\n"
"push 16\n"
"insc AllocMem\n"
"stw $ar, ($xr) 20\n"
"stw $r0, ($ar) 0\n"
"ret\n"
"CString.Pequals,R@Object?rhs:\n"
"ldw $cf, ($lb) -4\n"
"je .false\n"
"mov $tr, $cf\n"
"ldw $r0, ($xr) 4\n"
"ldw $r1, ($tr) 4\n"
"cmp $r0, $r1\n"
"jne .false\n"
"ldw $r0, ($xr) 12\n"
"ldw $r1, ($tr) 12\n"
"cmp $r0, $r1\n"
"jne .false\n"
"ldw $r2, ($xr) 20\n"
"ldw $r3, ($tr) 20\n"
".loop:\n"
"mov $cf, $r0\n"
"jle .break\n"
"ldw $r4, ($r2) 0\n"
"ldw $r5, ($r3) 0\n"
"cmp $r4, $r5\n"
"jne .false\n"
"inc $r2\n"
"inc $r3\n"
"dec $r0\n"
"jmp .loop\n"
".break:\n"
"mov $ar, 1\n"
"ret 1\n"
".false:\n"
"mov $ar, 0\n"
"ret 1\n"
"CString.Pinit,I?size:\n"
"call CString.Pinit\n"
"call CString.Presize,I?size\n"
"ret\n"
"CString.Pinit,R@String?source:\n"
"ldw $r0, ($lb) -4\n"
"push 20\n"
"push $r0\n"
"push $xr\n"
"insc CopyMem\n"
"ldw $r1, ($r0) 12\n"
"inc $r1\n"
"push $r1\n"
"insc AllocMem\n"
"stw $ar, ($xr) 20\n"
"ldw $r0, ($r0) 20\n"
"push $r1\n"
"push $r0\n"
"push $ar\n"
"insc CopyMem\n"
"ret 1\n"
"CString.PtoString:\n"
"mov $ar, $xr\n"
"ret\n"
"CString.Pcopy:\n"
"push @String.vtable\n"
"push 1\n"
"push 24\n"
"call new\n"
"pop $r1\n"
"ldw $r0, ($lb) -4\n"
"push $r1\n"
"push $r1\n"
"mov $xr, $r0\n"
"call CString.Pinit,R@String?source\n"
"pop $ar\n"
"ret\n"
"CString.Psize:\n"
"ldw $ar, ($xr) 12\n"
"dec $ar\n"
"ret\n"
"CString.Presize,I?size:\n"
"ldw $cf, ($lb) -4\n"
"jge .else\n"
"mov $cf, 0\n"
".else:\n"
"add $tr, $cf, 1\n"
"ldw $cf, ($xr) 12\n"
"cmp $cf, $tr\n"
"je .end\n"
"push $tr\n"
"call resize_buffer\n"
"ldw $r0, ($xr) 20\n"
"add $r0, $r0, $tr\n"
"mov $tr, 0\n"
"stw $tr, ($r0) 0\n"
".end:\n"
"ret 1\n"
"CString.Pempty:\n"
"ldw $cf, ($xr) 12\n"
"jg .not_empty\n"
"mov $ar, 1\n"
"ret\n"
".not_empty:\n"
"mov $ar, 0\n"
"ret\n"
"CString.Pappend,R@String?rhs:\n"
"ret 1\n"
"CString.Pappend,R@Object?rhs:\n"
"ret 1\n"
"CString.Pappend,B?rhs:\n"
"ret 1\n"
"CString.Pappend,I?rhs:\n"
"ret 1\n"
"CString.Pappend,F?rhs:\n"
"ret 1\n"
"CString.PsubString,I?pos,I?len:\n"
"ret 2\n"
"CString.PsetChar,I?pos,I?char:\n"
"ret 2\n"
"CString.PgetChar,I?pos:\n"
"mov $ar, 0\n"
"ret 1\n"
"CString.Ppointer:\n"
"ldw $ar, ($xr) 20\n"
"ret\n"
"String.vtable:\n"
".word @CString.Prelease\n"
".word @CString.Pinit\n"
".word @CObject.PtypeID\n"
".word @CObject.PrefCount\n"
".word @CString.Pequals,R@Object?rhs\n"
".word @CString.PtoString\n"
".word @CString.Ppointer\n"
".word @CString.Pinit,I?size\n"
".word @CString.Pinit,R@String?source\n"
".word @CString.Pcopy\n"
".word @CString.Psize\n"
".word @CString.Presize,I?size\n"
".word @CString.Pempty\n"
".word @CString.Pappend,R@String?rhs\n"
".word @CString.Pappend,R@Object?rhs\n"
".word @CString.Pappend,B?rhs\n"
".word @CString.Pappend,I?rhs\n"
".word @CString.Pappend,F?rhs\n"
".word @CString.PsubString,I?pos,I?len\n"
".word @CString.PsetChar,I?pos,I?char\n"
".word @CString.PgetChar,I?pos\n"
"CArray.Prelease:\n"
"ldw $r0, ($xr) 12\n"
"ldw $r1, ($xr) 20\n"
"mov $xr, $r1\n"
"sll $r0, $r0, 2\n"
"add $r0, $r0, $xr\n"
".loop:\n"
"cmp $xr, $r0\n"
"jge .end\n"
"push $xr\n"
"push $r0\n"
"push $r1\n"
"call dec_ref\n"
"pop $r1\n"
"pop $r0\n"
"pop $xr\n"
"add $xr, $xr, 4\n"
"jmp .loop\n"
".end:\n"
"push $r1\n"
"insc FreeMem\n"
"ret\n"
"CArray.Pinit:\n"
"CPrimArray.Pinit:\n"
"mov $r0, 0\n"
"stw $r0, ($xr) 12\n"
"mov $r1, 16\n"
"stw $r1, ($xr) 16\n"
"push 64\n"
"insc AllocMem\n"
"stw $ar, ($xr) 20\n"
"ret\n"
"CArray.Pinit,I?size:\n"
"ret 1\n"
"Array.vtable:\n"
".word @CArray.Prelease\n"
".word @CArray.Pinit\n"
".word @CObject.PtypeID\n"
".word @CObject.PrefCount\n"
"CBoolArray.Prelease:\n"
"ldw $r0, ($xr) 20\n"
"push $r0\n"
"insc FreeMem\n"
"ret\n"
"CBoolArray.Pinit:\n"
"ret\n"
"CBoolArray.Pinit,I?size:\n"
"ldw $cf, ($lb) -8\n"
"stw $cf, ($xr) 12\n"
"stw $cf, ($xr) 16\n"
"add $cf, $cf, 7\n"
"slr $cf, $cf, 3\n"
"push $cf\n"
"insc AllocMem\n"
"stw $ar, ($xr) 20\n"
"mov $r0, 0\n"
".loop:\n"
"jle .end\n"
"stw $r0, ($ar) 0\n"
"inc $ar\n"
"dec $cf\n"
"jmp .loop\n"
".end:\n"
"ret 1\n"
"BoolArray.vtable:\n"
".word @CBoolArray.Prelease\n"
".word @CBoolArray.Pinit\n"
".word @CObject.PtoString\n"
".word @CBoolArray.Pinit,I?size\n"
"CIntrinsics.PallocMem,I?size:\n"
"insc AllocMem\n"
"ret\n"
"CIntrinsics.PfreeMem,I?ptr:\n"
"insc FreeMem\n"
"ret\n"
"CIntrinsics.PcopyMem,I?destPtr,I?srcPtr,I?size:\n"
"insc CopyMem\n"
"ret\n"
"CIntrinsics.PsysCall,I?commandPtr:\n"
"insc SysCall\n"
"ret\n"
"CIntrinsics.Pprint,I?textPtr:\n"
"insc Print\n"
"ret\n"
"CIntrinsics.PprintLn,I?textPtr:\n"
"insc PrintLn\n"
"ret\n"
"CIntrinsics.PprintInt,I?value:\n"
"insc PrintInt\n"
"ret\n"
"CIntrinsics.PprintFloat,F?value:\n"
"insc PrintFloat\n"
"ret\n"
"CIntrinsics.Pinput,I?stringPtr,I?maxLen:\n"
"insc Input\n"
"ret\n"
"CIntrinsics.PinputInt:\n"
"insc InputInt\n"
"ret\n"
"CIntrinsics.PinputFloat:\n"
"insc InputFloat\n"
"ret\n"
"CIntrinsics.PcreateFile,I?filenamePtr:\n"
"insc CreateFile\n"
"ret\n"
"CIntrinsics.PdeleteFile,I?filenamePtr:\n"
"insc DeleteFile\n"
"ret\n"
"CIntrinsics.PopenFile,I?filenamePtr,I?modePtr:\n"
"insc OpenFile\n"
"ret\n"
"CIntrinsics.PcloseFile,I?handlePtr:\n"
"insc CloseFile\n"
"ret\n"
"CIntrinsics.PfileSetPos,I?handlePtr,I?offset,I?origin:\n"
"insc FileSetPos\n"
"ret\n"
"CIntrinsics.PfileGetPos,I?handlePtr:\n"
"insc FileGetPos\n"
"ret\n"
"CIntrinsics.PfileEOF,I?handlePtr:\n"
"insc FileEOF\n"
"ret\n"
"CIntrinsics.PwriteByte,I?handlePtr,I?value:\n"
"insc WriteByte\n"
"ret\n"
"CIntrinsics.PwriteInt,I?handlePtr,I?value:\n"
"insc WriteWord\n"
"ret\n"
"CIntrinsics.PwriteFloat,I?handlePtr,F?value:\n"
"insc WriteWord\n"
"ret\n"
"CIntrinsics.PwriteBuffer,I?handlePtr,I?bufferPtr,I?size:\n"
"insc WriteBuffer\n"
"ret\n"
"CIntrinsics.PreadByte,I?handlePtr:\n"
"insc ReadByte\n"
"ret\n"
"CIntrinsics.PreadInt,I?handlePtr:\n"
"insc ReadWord\n"
"ret\n"
"CIntrinsics.PreadFloat,I?handlePtr:\n"
"insc ReadWord\n"
"ret\n"
"CIntrinsics.PreadBuffer,I?handlePtr,I?bufferPtr,I?size:\n"
"insc ReadBuffer\n"
"ret\n"
"CIntrinsics.Psin,F?x:\n"
"insc Sin\n"
"ret\n"
"CIntrinsics.Pcos,F?x:\n"
"insc Cos\n"
"ret\n"
"CIntrinsics.Ptan,F?x:\n"
"insc Tan\n"
"ret\n"
"CIntrinsics.Pasin,F?x:\n"
"insc ASin\n"
"ret\n"
"CIntrinsics.Pacos,F?x:\n"
"insc ACos\n"
"ret\n"
"CIntrinsics.Patan,F?x:\n"
"insc ATan\n"
"ret\n"
"CIntrinsics.Ppow,F?b,F?e:\n"
"insc Pow\n"
"ret\n"
"CIntrinsics.Plog,F?x:\n"
"insc Log\n"
"ret\n"
"CIntrinsics.Plog2,F?x:\n"
"insc Log2\n"
"ret\n"
"CIntrinsics.Plog10,F?x:\n"
"insc Log10\n"
"ret\n"
"CIntrinsics.Psqrt,F?x:\n"
"insc Sqrt\n"
"ret\n"
"CIntrinsics.PrandInt:\n"
"insc RandInt\n"
"ret\n"
"CIntrinsics.PrandFloat:\n"
"insc RandFloat\n"
"ret\n"
"CIntrinsics.Ptime:\n"
"insc Time\n"
"ret\n"
"CIntrinsics.Psleep,I?duration:\n"
"insc Sleep\n"
"ret\n"
